### ISSUE TITLE
permit country name as well as ISO2 code

### ISSUE THREAD

**Issue by PeteMcM** [vincentarelbundock/WDI#21]
Hi Vincent,
Only just learnt of this very useful library. It would be great if country = (...) could be extended to allow a vector of names in lieu of ISO2 code. Eg country = c("New Zealand", "Australia", ...).
Kind regards,
Pete McMillen

**Comment by fxi** [comment]
You can convert country names to ISO2 with the package "countrycode".
```{r}
devtools::install_github("vincentarelbundock/countrycode")
# or
install.packages('countrycode')
```

Then: 
```{r}
# countrycode("countries to convert", "code input", "code output")
countrycode("Venezuela", "country.name", "iso2c")
#[1] "VE"
countrycode("Yemen People's Republic", "country.name", "iso2c")
# [1] "YD"
```

With WDI and ggplot:
```{r}
library(WDI)
library(ggplot2)

dat = WDI(
    indicator = 'NY.GDP.PCAP.KD', 
    country = countrycode('Mozambique','country.name','iso2c'), 
    start = 1980, 
    end = 2012
)

ggplot(
  data = dat, 
  aes(
    x = year, 
    y = NY.GDP.PCAP.KD, 
    color = country)
  ) + 
geom_line() + 
xlab('Year') + 
ylab('GDP per capita')
```

**Comment by vincentarelbundock** [comment]
Thanks for the suggestion. I agree with @fxi . This is best handled separately by countrycode (Hey! Synergy between my packages!)
