### ISSUE TITLE
Population indicator incorrect/missing

### ISSUE THREAD

**Issue by kendonB** [vincentarelbundock/WDI#22]
```
indic <- WDIsearch("Population, millions")[1] 
my_wdi <- WDI(indicator = indic, start = 2000, end = 2000)
Warning message:
In WDI(indicator = indic, start = 2000, end = 2000) :
  Unable to download indicators  SPPOPTOTL
```

**Comment by gralgomez** [comment]
I had exact the same issue. Apparently the indicator is misspelled at the WDIsearch. Try SP.POP.TOTL

**Comment by vincentarelbundock** [comment]
This was fixed here: https://github.com/vincentarelbundock/WDI/commit/76e9d278e7b641d5f04bc4599fea74b63312024d

Please install the Github version

**Comment by vincentarelbundock** [comment]
library(devtool)
install_github('vincentarelbundock/WDI')
