### ISSUE TITLE
error message with Social protection indicators in WDI R package 

### ISSUE THREAD

**Issue by haitmansour** [vincentarelbundock/WDI#24]
Hello,

I'm trying to download Social protection data using WDI R package. The WDIsearch("Social protection") gives more than 140 social protectiojn indicator but only one of them works. ("IQ.CPA.PROT.XQ"). Other indicators such as ""per_allsp.adq_ep_preT_tot"  , "per_allsp.adq_ep_tot"  "per_allsp.adq_pop_preT_tot", along the list don't work. here is the code as well as the error message i got:

HIC<- WDI(indicator= c("per_allsp.adq_ep_preT_tot"),country= c("BH", "KW", "OM", "QA", "SA", "AE", "BN"), start=2000, end=2014)

Warning message:
In WDI(indicator = c("per_allsp.adq_ep_preT_tot"), country = c("BH",  :
  Unable to download indicators  perallsp.adqeppreTtot

Many thanks for your help

All the best
hicham

**Comment by vincentarelbundock** [comment]
Is it possible the indicators you're trying to get are just not available for those country-years? Things seem to work for me, but data is sparse:

    library(WDI)
    z = WDIcache()
    z = WDIsearch(‘social protection’, cache=z)
    z = z[, ‘indicator’]
    dat = WDI(indicator=z, country=‘all’)
    dim(dat)
    [1] 1764  160

**Comment by haitmansour** [comment]
Thanks, i tried your code, it gave me this:
Error: unexpected input in "z = WDIsearch(‘"
> z = z[, ‘indicator’]
Error: unexpected input in "z = z[, ‘"
> dat = WDI(indicator=z, country=‘all’)
Error: unexpected input in "dat = WDI(indicator=z, country=‘"

**Comment by vincentarelbundock** [comment]
curved quotes were copied over from textedit. try again.

**Comment by haitmansour** [comment]
Thanks, i replaced single quote with double quotes in your code and it worked, but only one indicator is available. For the rest i got the following warning message: 
Warning message:
In WDI(indicator = z, country = "all") :
  Unable to download indicators  FC.XPD.PROT.CR ; perallsp.adqeppreTtot ; perallsp.adqeptot ; perallsp.adqpoppreTtot ; perallsp.adqpoprur ; perallsp.adqpoptot ; perallsp.adqpopurb ; perallsp.adqq1preTtot ; perallsp.adqq1rur ; perallsp.adqq1tot ; perallsp.adqq1urb ; perallsp.adqq2preTtot ; perallsp.adqq2rur ; perallsp.adqq2tot ; perallsp.adqq2urb ; perallsp.adqq3preTtot ; perallsp.adqq3rur ; perallsp.adqq3tot ; perallsp.adqq3urb ; perallsp.adqq4preTtot ; perallsp.adqq4rur ; perallsp.adqq4tot ; perallsp.adqq4urb ; perallsp.adqq5preTtot ; perallsp.adqq5rur ; perallsp.adqq5tot ; perallsp.adqq5urb ; perallsp.avteppreTtot ; perallsp.avteptot ; perallsp.avtpoppreTtot ; perallsp.avtpoprur ; perallsp.avtpoptot ; perallsp.avtpopurb ; perallsp.avtq1preTtot ; perallsp.avtq1rur ; perallsp.avtq1tot ; perallsp.avtq1urb ; perallsp.avtq2preTtot ; perallsp.avtq2rur ; perallsp.avtq2tot ; perallsp.avtq2urb ; perallsp.avtq3preTtot ; perallsp.avtq3rur ; perallsp.avtq3tot ; perallsp.avtq3urb ; perallsp.avtq4pr [... truncated]

**Comment by vincentarelbundock** [comment]
This is strange. Try updating the package to its latest github version:

    library(devtools)
    install_github('vincentarelbundock/WDI')

**Comment by haitmansour** [comment]
This has finally worked when i updated using your code. Thank you very much. there is lot of missing data but still many indicators has data for half of my countries of interest!

**Comment by vincentarelbundock** [comment]
glad i was able to help

**Comment by haitmansour** [comment]
Do you knwo if there is a quick way to rename the indicators using their names instead of their code? many thanks again

**Comment by vincentarelbundock** [comment]
you should be able to do that in a couple lines of code using ``match``

**Comment by haitmansour** [comment]
Great, any leads on how to use the match please?

**Comment by vincentarelbundock** [comment]
no

**Comment by haitmansour** [comment]
i've been doing this manually using names(x) [1]="" but the list of indicators is very long

**Comment by haitmansour** [comment]
thanks anyway, greetings from Morocco
