### ISSUE TITLE
WDI_data.RData outdated

### ISSUE THREAD

**Issue by muuankarski** [vincentarelbundock/WDI#25]
I was looking for the poverty headcount ratios that [WB recently changed](http://blogs.worldbank.org/developmenttalk/international-poverty-line-has-just-been-raised-190-day-global-poverty-basically-unchanged-how-even). Even though API returns up-to-date data, the `data/WDI_data.RData` file has old names, for example showing, `$1,25` poverty line instead of the current `$1.90`.  Any plans to update that file?

Thanks,
Markus

**Comment by vincentarelbundock** [comment]
Done on github: https://github.com/vincentarelbundock/WDI/commit/e872c85200d58588bc12b810ffa38ae1021a9f94
