### ISSUE TITLE
Feature request: add an option to exclude aggregates

### ISSUE THREAD

**Issue by LaDilettante** [vincentarelbundock/WDI#27]
Specifying `extra = TRUE` includes the column `region`, which indicates which row is an aggregate. Based on this, one can exclude aggregates by himself.

However, it would be convenient to have an option in the main command to exclude aggregates.

**Comment by vincentarelbundock** [comment]
Thanks for the suggestion, but I prefer to keep the number of arguments in the WDI function to a minimum, unless the proposed function adds a lot of convenience. Here, we're only talking about saving (some subset of users) 1 line of code. So I think I'll be closing this. Sorry!
