### ISSUE TITLE
underscores in indicator names

### ISSUE THREAD

**Issue by gdkrmr** [vincentarelbundock/WDI#28]
```R
> WDIsearch("WP11623_4.1", field = "indicator")
     indicator     
[1,] "WP11623_4.1" 
[2,] "WP11623_4.10"
[3,] "WP11623_4.11"
     name                                                          
[1,] "Account at a formal financial institution (% age 15+)"       
[2,] "Account at a formal financial institution, rural (% age 15+)"
[3,] "Account at a formal financial institution, urban (% age 15+)"
> WDI(country = "all", indicator = "WP11623_4.1")
NULL
Warning message:
In WDI(country = "all", indicator = "WP11623_4.1") :
  Unable to download indicators  WP116234.1
```

**Comment by MatthieuStigler** [comment]
Facing the same issue! I guess this is due to the first line of code:

    indicator = gsub("[^a-zA-Z0-9\\.]", "", indicator)

Which removes the underscore, hence cannot read anymore! So adding _ to the list would easily solve this!!

It seems this affects many variables, close to 761?

    >  all <- WDI_data$series[,"indicator"]
    > sum(grepl("_", all))
    [1] 761

**Comment by vincentarelbundock** [comment]
in the latest github version, it seems like the offending line is commented out. Can you try installing that one?

**Comment by MatthieuStigler** [comment]
Solve indeed, thanks!

**Comment by vincentarelbundock** [comment]
thanks for checking. I really hate submitting to CRAN, so unfortunately, I'm not sure when I'll get around to putting out an official new release. At least it's fixed for those motivate enough to check here :)
