### ISSUE TITLE
Add functionality to pull most recent data available

### ISSUE THREAD

**Issue by paulecon** [vincentarelbundock/WDI#29]
Many WDI indicators are not calculated every year for every country, and they are updated at different times (see, for example, SP.POP.TECH.RD.P6).  The World Bank wbopendata Stata module has a "latest" functionality, and I would love to see the same option for the R package.  I've created a quick workaround in my code, but this requires pulling the last 5 years of data, ordering it by country and year, and removing duplicate country records.

**Comment by vincentarelbundock** [comment]
I'd be willing to review a PR for this (perhaps we should create new function WDI_latest. However, I have basically zero time to invest for improvements to the package, so I'm afraid this functionality will not be implemented without a (pretty much complete) PR.

**Comment by etiennebacher** [comment]
I'm okay to work on this, but I don't really understand the feature. Get the last year? The last year for which all countries have a value? What if there is no year where all countries have a value?

**Comment by vincentarelbundock** [comment]
Not sure I understand the request either. FWIW, this is the only mention I can find in the Stata docs:

https://github.com/jpazvd/wbopendata/blob/master/src/w/wbopendata.sthlp#L33

```stata
{synopt :{opt latest}} keep only the latest available value of a single indicator.{p_end}
```

Is the request equivalent to this?

```r
library(WDI)
library(dplyr)

WDI() %>%
  drop_na %>%
  arrange(iso3c, year) %>%
  group_by(iso3c) %>%
  tail(1)
```

If so, I'm not convinced it is worth adding a new argument for it. But I'm open to convincing if there are strong arguments in favor and I understood the proposal correctly.

**Comment by etiennebacher** [comment]
Turns out there are arguments for this in World Bank API on [this page](https://datahelpdesk.worldbank.org/knowledgebase/articles/898581-api-basic-call-structures): MRV (for Most Recent Values) and MRNEV (for Most Recent Non-Empty Values). These could be additional arguments to `WDI()` without necessarily create a new function.

But I still have trouble understanding what they produce.

**Comment by vincentarelbundock** [comment]
Oh that's interesting (even if we don't know what it means). Would be pretty easy to add one argument that controls both of these options, I think.
