### ISSUE TITLE
iso3c code missing for some countries

### ISSUE THREAD

**Issue by Napho** [vincentarelbundock/WDI#32]
```
library(WDI)
WDI(country='SZ', indicator='NY.GDP.MKTP.CD', extra = TRUE)
```

Returned data set has iso3c code for Swaziland missing.
Same codes are do exist in excel download from WDI site

**Comment by vincentarelbundock** [comment]
Thanks for the report. Fixed here: https://github.com/vincentarelbundock/WDI/commit/34854bb9a06ebacfa9a2905f164256b6561dd0b9

Will be updated on CRAN soon.
