### ISSUE TITLE
Region names became codes

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/WDI#36]
Following #35, I ran:
```
library(remotes)
remove.packages(c('RJSONIO', 'WDI'))
install_github('vincentarelbundock/WDI')
library(WDI)
```
I would like to download region names as well and added `extra = TRUE`:
```
WDI(country = "FRA", indicator = "NV.AGR.TOTL.ZS", extra = TRUE)
```
This worked before (I used it three months ago but not until today), but now the column `region` provides some code like `Z7` instead of `Europe & Central Asia`. Is it possible to fix it?

Thanks for the nice package.

**Comment by vincentarelbundock** [comment]
Thanks a lot for this report. I believe I found the bug. Could you please install from Github, restart your R session, and try again?

```r
library(remotes)
install_github('vincentarelbundock/WDI')

library(WDI)
WDI(country = "FRA", indicator = "NV.AGR.TOTL.ZS", extra = TRUE)
```

**Comment by etiennebacher** [comment]
Perfect, it works now
