### ISSUE TITLE
Submit to rOpenSci?

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/WDI#40]
Hi, I was wondering if you plan on submitting `WDI` to [rOpenSci](https://ropensci.org). This would allow to have a proper peer-review (along with [other advantages](https://github.com/ropensci/software-review#why-submit)), though the package is quite simple and works very well. This would take some additional time if there are some modifications needed after the review, but I think that having a package supported by rOpenSci is a great indicator of reliability for users.

Of course, `WDI` is already very good as-is (and thanks for having built it!). It was just something crossing my mind while checking the list of rOpenSci packages.

**Comment by vincentarelbundock** [comment]
Interesting. To be honest, I'm not super familiar with `rOpenSci`.

I'm sure they could offer useful suggestions for code structure, documentation, etc. But the functionality of the package is pretty minimalist, and as you noted it "works" and it's reasonably well documented.

One path for future improvement would be to scour the World Bank API docs to see if there is something that is not currently supported. I would be very interested in adding such features, but I don't currently have the bandwidth to go through the WB docs in detail to figure this out.

I suppose that could help the package get more attention, but to be frank, I'm pretty indifferent to usage level. It's really great if people find it useful, but I'm not sure I'm willing to spend hours on code review to get a few dozen more users.

Re-reading the above, it sounds too negative. I'm sure `rOpenSci` does really great work, and I think that promoting software quality and recognition is super important in the open source community. I'm just not sure the cost-benefit works for me w.r.t. this particular project.

As always, I'm open to counter-arguments ;)

**Comment by etiennebacher** [comment]
Sure, I completely understand your arguments, and I have no problems with that. As I said, the package already seems robust. ;)

For reference, here are a few links that could give ideas for new features:

* [New features in V2](https://datahelpdesk.worldbank.org/knowledgebase/articles/1886674-new-features-and-enhancements-in-the-v2-api)
* [Advanced Data API Queries (BETA)](https://datahelpdesk.worldbank.org/knowledgebase/articles/1886686-advanced-data-api-queries), to get the dataset as it existed in 1997 for example.
* [Other World Bank APIs](https://datahelpdesk.worldbank.org/knowledgebase/articles/889386) (this is maybe out of the scope of `WDI`, but it gives ideas).
