### ISSUE TITLE
renaming on the fly not working anymore

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/WDI#47]
Test with documentation example:
```
# Rename indicators on the fly
WDI(country = 'CA', indicator = c('women_private_sector' = 'BI.PWK.PRVS.FE.ZS',
                                  'women_public_sector' = 'BI.PWK.PUBS.FE.ZS'))

iso2c country year BI.PWK.PRVS.FE.ZS BI.PWK.PUBS.FE.ZS
1    CA  Canada 2000                NA                NA
2    CA  Canada 2001                NA                NA
3    CA  Canada 2002                NA                NA
4    CA  Canada 2003                NA                NA
5    CA  Canada 2004                NA                NA
6    CA  Canada 2005                NA                NA
...
```
Tested with last CRAN and GitHub versions (2.7.3)

**Comment by vincentarelbundock** [comment]
Thanks a lot for the report. Looks like I introduced a stupid bug in the latest release (calling `unique(indicators)` strips vector names). I just commited a fix to Github and submitted an emergency bug fix release (2.7.4) to CRAN.

**Comment by vincentarelbundock** [comment]
I also added a test for this, and received notification that the package has been accepted and is on its way to CRAN.

Thanks again!

**Comment by etiennebacher** [comment]
Thanks a lot for the quick fix!
