### ISSUE TITLE
WDIcodebook(indicator, cache=NULL)

### ISSUE THREAD

**Issue by vincentarelbundock** [vincentarelbundock/WDI#5]
Generate a nicely formatted rst file with codebook info about a list of indicators

**Comment by vincentarelbundock** [comment]
Realistically, I'm not going to do this. Closing until someone motivated comes along.

**Comment by etiennebacher** [comment]
Hi, this is an old but apparently not solved issue. I could work on that if I had a bit more info (and if it's still relevant today). Is the codebook the same thing as [this stuff](http://api.worldbank.org/v2/datacatalog)?

**Comment by vincentarelbundock** [comment]
Yeah, that's more or less what I had in mind. Also relevant might be `WDI::WDI_data$series`.

9 years later, I think maybe Markdown is more commonly used in the `R` universe than python's RST.

**Comment by etiennebacher** [comment]
`WDI::WDI_data$series` already gives some description for each indicator so I'm not sure what you wanted to add. Is it like transforming this into a PDF codebook? The link I provided only gives some details on the big families of indicators (WDI, Millenium Development Goals, etc.) so I'm not really sure of the value added of this.

**Comment by vincentarelbundock** [comment]
Yes, I think I agree with your assessment.

My initial thought was that it would be nice to create a single vector `ind` with your list of indicators. You could then feed that to `WDI` and `WDIcodebook` and get both your original data and a neat codebook to include in the appendix of your paper. 

But I agree that this is probably of limited use and not worth investing much in, which is probably why I closed the issue originally :-D

**Comment by etiennebacher** [comment]
Aaah ok now I get it! That was completely different from what I had in mind ^^ Indeed I guess people would prefer something that matches the "design" of their work so it might be better to do that individually
