### ISSUE TITLE
ISO2 vs ISO3?

### ISSUE THREAD

**Issue by mabuimo** [vincentarelbundock/WDI#53]
Not a bug, just a question, why if you download any indicator in csv format you get the country code with three letters, but if you download it using your package the country code has just 2 letters?

**Comment by vincentarelbundock** [comment]
Simply because the world bank has decided to include different info in their CSV files ans API calls.

:)

**Comment by mabuimo** [comment]
Fair enough! I was wondering if maybe you had removed the ISO3 code :)

**Comment by vincentarelbundock** [comment]
No, I didn't. But -- and I should have said that earlier -- you can request ISO3c with the `extra` argument. `WDI` will then draw info from a different source and merge it automatically for you.

Hope that helps!
