### ISSUE TITLE
Differences in WDI data using R::WDI and Stata::wbopendata

### ISSUE THREAD

**Issue by gronert-m** [vincentarelbundock/WDI#56]
I was using your R package to export subsets of data by income levels of countries to Excel as I was not finding Stata helpful for this.

However, I noticed differences in the data itself. Using the following in Stata 

```
wbopendata, indicator(SP.POP.TOTL) long clear latest
list if countrycode == "NPL"
```
results in 

![stata](https://user-images.githubusercontent.com/63501500/152145775-1fe72aaa-f0ad-4b70-b423-4a02a3be357a.PNG)

With R::WDI

```
df <- WDI::WDI(country = "all", indicator = "SP.POP.TOTL", latest = 1, extra = TRUE)
df[df$iso3c == "NPL",]
```

results in 

![R](https://user-images.githubusercontent.com/63501500/152145905-07f96453-2061-4d56-810a-d05506836464.PNG)

So year and population numbers match. Nepal had 29,136,808 inhabitants in 2020. However, using Stata I am told that Nepal is a "lower middle income" country while using the R tool I am told Nepal is "lower income".

What explains this behaviour? Am I doing something wrong?

P.S.: Otherwise and of course, thanks for the package! :)

**Comment by vincentarelbundock** [comment]
I need to update the package cache. In the meantime, you can do it manually by:

```{r}
library(WDI)
cache <- WDIcache()
df <- WDI::WDI(country = "all", indicator = "SP.POP.TOTL", latest = 1, extra = TRUE, cache = cache)
df[df$iso3c %in% "NPL",]
```

**Comment by vincentarelbundock** [comment]
on its way to the CRAN servers now

**Comment by gronert-m** [comment]
Much appreciated!
