### ISSUE TITLE
Difference in data downloaded and what is seen on WDI website

### ISSUE THREAD

**Issue by vikasrawal** [vincentarelbundock/WDI#57]
I am trying to download per capital GDP (NY.GDP.PCAP.KD) for all countries. But the data are mostly blanks (except for region aggregates), while the WDI website has the data.

**Comment by vincentarelbundock** [comment]
I just tried on my computer and it works fine. Make sure you are using the latest version of the package, restart R, and try again.

If it still does not work, please provide more information about your environment via `sessionInfo()` and show me exactly how many missing data points there are for which countries, etc.

Minimal working example is key.

**Comment by vincentarelbundock** [comment]
In the screenshot the data are not missing. There are multiple GDP current indicators available; you could try another. Please contact the World Bank to know why the data from their API differs from the data on the website.

**Comment by etiennebacher** [comment]
@embruna The package provides the correct data. The thing is that `6.0.GDP_current` only has data for South America and 2000-2014: https://databank.worldbank.org/source/lac-equity-lab-/Series/6.0.GDP_current

(I don't know why though)

**Comment by vincentarelbundock** [comment]
Thanks @etiennebacher !

**Comment by vincentarelbundock** [comment]
@embruna I agree this is confusing, so adding a clarification sounds like a great idea! I'll be happy to merge a pull request if you put one together.

I think I'd lean toward something in the documentation. Strictly speaking, `WDI` is doing exactly what the user is requesting, so it feels weird and intrusive to raise a warning or a message. A clarification in the documentation seems like a no-brainer, though.

**Comment by vincentarelbundock** [comment]
I welcome anyone to open a PR with improved documentation, but am going to close this to tidy up the repo and keep only the issues I am actively working on.
