### ISSUE TITLE
How to download average world GDP per capita (constant 2015 US$) by using WDI

### ISSUE THREAD

**Issue by junjun987** [vincentarelbundock/WDI#61]
Hi,I'm sorry to bother you.I'm a new beginner of R.I want to use WDI to download global GDP per capita (constant 2015 US$) ,like this figrue.But I don't know how to define country in wdi.I only get all country of GDP,but I can't get a global data

<img width="618" alt="image" src="https://user-images.githubusercontent.com/113010390/194991409-b82bb183-20ad-44d8-9478-0c354a4dd880.png">

**Comment by junjun987** [comment]
Hi,thank you for your reply.I konw how to solve my problems in R studio community. I set the command "country=1W",that it work

**Comment by vincentarelbundock** [comment]
Great news!
