### ISSUE TITLE
Most queries fail due to redirection to the "Boost portal"

### ISSUE THREAD

**Issue by etiennebacher** [vincentarelbundock/WDI#63]
Hi Vincent, most of the links to the WDI API stopped working and now redirect to the "Boost portal", which makes queries fail. This is even the case for links posted in the ["Data HelpDesk page"](https://datahelpdesk.worldbank.org/knowledgebase/articles/898599-indicator-api-queries) of the World Bank, e.g http://api.worldbank.org/v2/indicator/NY.GDP.MKTP.CD.

I know you can't do much about that, but I was wondering if you had already contacted some people at the World Bank for similar problems in the past. If so, could you contact them again? I would do that if I knew how, but the "Contact support" link on the HelpDesk page doesn't do anything (it has no link attached to it...). 

At the same time, this issue might be useful for other people to know that it's not a problem with the package.

Thanks

**Comment by vincentarelbundock** [comment]
Thanks, I got some emails about this from users. I contacted the WB support and am waiting for a reply.

**Comment by etiennebacher** [comment]
Looks like this is solved
